## Deliverable 2. Create a Customer Travel Destinations Map.

In [22]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("C:/Users/dtj13/Documents/Data Analytics Course/Module_6_API/World_Weather_Analysis/Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Olafsvik,IS,64.8945,-23.7142,40.10,77,93,12.39,overcast clouds
1,1,Port Alfred,ZA,-33.5906,26.8910,60.46,83,22,12.64,few clouds
2,2,Toma,BF,12.7667,-2.8833,83.34,41,85,7.96,overcast clouds
3,3,Rikitea,PF,-23.1203,-134.9692,73.74,79,39,19.06,light rain
4,4,Kapaa,US,22.0752,-159.3190,82.72,69,20,4.00,few clouds

In [10]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 0
What is the maximum temperature you would like for your trip? 300

In [11]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Olafsvik,IS,64.8945,-23.7142,40.10,77,93,12.39,overcast clouds
1,1,Port Alfred,ZA,-33.5906,26.8910,60.46,83,22,12.64,few clouds
2,2,Toma,BF,12.7667,-2.8833,83.34,41,85,7.96,overcast clouds
3,3,Rikitea,PF,-23.1203,-134.9692,73.74,79,39,19.06,light rain
4,4,Kapaa,US,22.0752,-159.3190,82.72,69,20,4.00,few clouds
5,5,Atuona,PF,-9.8000,-139.0333,78.03,79,68,18.66,light rain
6,6,Busselton,AU,-33.6500,115.3333,51.10,63,33,4.29,scattered clouds
7,7,Lagoa,PT,39.0500,-27.9833,72.01,84,85,10.02,overcast clouds
8,8,Albany,US,42.6001,-73.9662,60.39,95,100,0.67,overcast clouds
9,9,Vaini,TO,-21.2000,-175.2000,80.76,78,40,9.22,scattered clouds

In [14]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()
preferred_cities_df.isnull().sum()

Unnamed: 0             0
City                   0
Country                4
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [16]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Olafsvik,IS,40.10,overcast clouds,64.8945,-23.7142,
1,Port Alfred,ZA,60.46,few clouds,-33.5906,26.8910,
2,Toma,BF,83.34,overcast clouds,12.7667,-2.8833,
3,Rikitea,PF,73.74,light rain,-23.1203,-134.9692,
4,Kapaa,US,82.72,few clouds,22.0752,-159.3190,
5,Atuona,PF,78.03,light rain,-9.8000,-139.0333,
6,Busselton,AU,51.10,scattered clouds,-33.6500,115.3333,
7,Lagoa,PT,72.01,overcast clouds,39.0500,-27.9833,
8,Albany,US,60.39,overcast clouds,42.6001,-73.9662,
9,Vaini,TO,80.76,scattered clouds,-21.2000,-175.2000,

In [21]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [26]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Olafsvik,IS,40.10,overcast clouds,64.8945,-23.7142,Hotel Olafsvik
1,Port Alfred,ZA,60.46,few clouds,-33.5906,26.8910,The Halyards Hotel
2,Toma,BF,83.34,overcast clouds,12.7667,-2.8833,Auberge de l'amitié
3,Rikitea,PF,73.74,light rain,-23.1203,-134.9692,People ThankYou
4,Kapaa,US,82.72,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
...,...,...,...,...,...,...,...
729,Bageshwar,IN,61.90,clear sky,29.8500,79.7667,Danu Janral Store
730,Galveston,US,83.17,clear sky,29.3669,-94.9669,Comfort Inn & Suites Texas City
731,Xinxiang,CN,53.76,light rain,35.3089,113.8672,Guoyu Holiday Inn
732,Koumac,NC,80.28,clear sky,-20.5667,164.2833,Le Monitel
733,Arawa,PG,86.34,overcast clouds,-6.2132,155.5367,Coastline Guest House

In [28]:
# 8a. Create the output File (CSV)
clean_hotel_file = ("C:/Users/dtj13/Documents/Data Analytics Course/Module_6_API/World_Weather_Analysis/Vacation_Search/WeatherPy_vacation.csv")
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(clean_hotel_file, index_label="City_ID")

In [29]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [32]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.3)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))